/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_AD_25 (coord M15), LPUART1_RXD */
/* Routed pin properties */
#define BOARD_INITLPUARTPINS_LPUART1_RXD_PERIPHERAL                      LPUART1   /*!< Peripheral name */
#define BOARD_INITLPUARTPINS_LPUART1_RXD_SIGNAL                              RXD   /*!< Signal name */

/* GPIO_AD_24 (coord L13), LPUART1_TXD */
/* Routed pin properties */
#define BOARD_INITLPUARTPINS_LPUART1_TXD_PERIPHERAL                      LPUART1   /*!< Peripheral name */
#define BOARD_INITLPUARTPINS_LPUART1_TXD_SIGNAL                              TXD   /*!< Signal name */

/* GPIO_EMC_B2_18 (coord N3), USER_GREEN */
/* Routed pin properties */
#define BOARD_INITLPUARTPINS_USER_GREEN_PERIPHERAL                         GPIO8   /*!< Peripheral name */
#define BOARD_INITLPUARTPINS_USER_GREEN_SIGNAL                           gpio_io   /*!< Signal name */
#define BOARD_INITLPUARTPINS_USER_GREEN_CHANNEL                              28U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLPUARTPINS_USER_GREEN_GPIO                               GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITLPUARTPINS_USER_GREEN_GPIO_PIN                             28U   /*!< GPIO pin number */
#define BOARD_INITLPUARTPINS_USER_GREEN_GPIO_PIN_MASK                (1U << 28U)   /*!< GPIO pin mask */

/* GPIO_AD_08 (coord R15), USER_RED */
/* Routed pin properties */
#define BOARD_INITLPUARTPINS_USER_RED_PERIPHERAL                           GPIO9   /*!< Peripheral name */
#define BOARD_INITLPUARTPINS_USER_RED_SIGNAL                             gpio_io   /*!< Signal name */
#define BOARD_INITLPUARTPINS_USER_RED_CHANNEL                                 7U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLPUARTPINS_USER_RED_GPIO                                 GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITLPUARTPINS_USER_RED_GPIO_PIN                                7U   /*!< GPIO pin number */
#define BOARD_INITLPUARTPINS_USER_RED_GPIO_PIN_MASK                   (1U << 7U)   /*!< GPIO pin mask */

/* GPIO_AD_10 (coord R17), USER_BLUE */
/* Routed pin properties */
#define BOARD_INITLPUARTPINS_USER_BLUE_PERIPHERAL                          GPIO9   /*!< Peripheral name */
#define BOARD_INITLPUARTPINS_USER_BLUE_SIGNAL                            gpio_io   /*!< Signal name */
#define BOARD_INITLPUARTPINS_USER_BLUE_CHANNEL                                9U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLPUARTPINS_USER_BLUE_GPIO                                GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITLPUARTPINS_USER_BLUE_GPIO_PIN                               9U   /*!< GPIO pin number */
#define BOARD_INITLPUARTPINS_USER_BLUE_GPIO_PIN_MASK                  (1U << 9U)   /*!< GPIO pin mask */

/* WAKEUP (coord T8), USER_S1 */
/* Routed pin properties */
#define BOARD_INITLPUARTPINS_USER_S1_PERIPHERAL                           GPIO13   /*!< Peripheral name */
#define BOARD_INITLPUARTPINS_USER_S1_SIGNAL                              gpio_io   /*!< Signal name */
#define BOARD_INITLPUARTPINS_USER_S1_CHANNEL                                  0U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLPUARTPINS_USER_S1_GPIO                                 GPIO13   /*!< GPIO peripheral base pointer */
#define BOARD_INITLPUARTPINS_USER_S1_GPIO_PIN                                 0U   /*!< GPIO pin number */
#define BOARD_INITLPUARTPINS_USER_S1_GPIO_PIN_MASK                    (1U << 0U)   /*!< GPIO pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLpuartPins(void);              /* Function assigned for the Cortex-M7F */

/* GPIO_AD_29 (coord M17), DSI_EN */
/* Routed pin properties */
#define BOARD_INITMIPIPANELPINS_DSI_EN_PERIPHERAL                          GPIO9   /*!< Peripheral name */
#define BOARD_INITMIPIPANELPINS_DSI_EN_SIGNAL                            gpio_io   /*!< Signal name */
#define BOARD_INITMIPIPANELPINS_DSI_EN_CHANNEL                               28U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMIPIPANELPINS_DSI_EN_GPIO                                GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITMIPIPANELPINS_DSI_EN_GPIO_PIN                              28U   /*!< GPIO pin number */
#define BOARD_INITMIPIPANELPINS_DSI_EN_GPIO_PIN_MASK                 (1U << 28U)   /*!< GPIO pin mask */

/* GPIO_EMC_B2_00 (coord K2), LPI2C2_SCL */
/* Routed pin properties */
#define BOARD_INITMIPIPANELPINS_LPI2C2_SCL_PERIPHERAL                     LPI2C2   /*!< Peripheral name */
#define BOARD_INITMIPIPANELPINS_LPI2C2_SCL_SIGNAL                            SCL   /*!< Signal name */

/* GPIO_EMC_B2_01 (coord K4), LPI2C2_SDA */
/* Routed pin properties */
#define BOARD_INITMIPIPANELPINS_LPI2C2_SDA_PERIPHERAL                     LPI2C2   /*!< Peripheral name */
#define BOARD_INITMIPIPANELPINS_LPI2C2_SDA_SIGNAL                            SDA   /*!< Signal name */

/* GPIO_AD_30 (coord K17), DSI_TS_INT */
/* Routed pin properties */
#define BOARD_INITMIPIPANELPINS_DSI_TS_INT_PERIPHERAL                      GPIO9   /*!< Peripheral name */
#define BOARD_INITMIPIPANELPINS_DSI_TS_INT_SIGNAL                        gpio_io   /*!< Signal name */
#define BOARD_INITMIPIPANELPINS_DSI_TS_INT_CHANNEL                           29U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMIPIPANELPINS_DSI_TS_INT_GPIO                            GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITMIPIPANELPINS_DSI_TS_INT_GPIO_PIN                          29U   /*!< GPIO pin number */
#define BOARD_INITMIPIPANELPINS_DSI_TS_INT_GPIO_PIN_MASK             (1U << 29U)   /*!< GPIO pin mask */

/* GPIO_AD_05 (coord P13), DSI_TS_RST */
/* Routed pin properties */
#define BOARD_INITMIPIPANELPINS_DSI_TS_RST_PERIPHERAL                      GPIO9   /*!< Peripheral name */
#define BOARD_INITMIPIPANELPINS_DSI_TS_RST_SIGNAL                        gpio_io   /*!< Signal name */
#define BOARD_INITMIPIPANELPINS_DSI_TS_RST_CHANNEL                            4U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMIPIPANELPINS_DSI_TS_RST_GPIO                            GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITMIPIPANELPINS_DSI_TS_RST_GPIO_PIN                           4U   /*!< GPIO pin number */
#define BOARD_INITMIPIPANELPINS_DSI_TS_RST_GPIO_PIN_MASK              (1U << 4U)   /*!< GPIO pin mask */

/* GPIO_AD_15 (coord M14), LCD_RST_B */
/* Routed pin properties */
#define BOARD_INITMIPIPANELPINS_LCD_RST_B_PERIPHERAL                       GPIO9   /*!< Peripheral name */
#define BOARD_INITMIPIPANELPINS_LCD_RST_B_SIGNAL                         gpio_io   /*!< Signal name */
#define BOARD_INITMIPIPANELPINS_LCD_RST_B_CHANNEL                            14U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMIPIPANELPINS_LCD_RST_B_GPIO                             GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITMIPIPANELPINS_LCD_RST_B_GPIO_PIN                           14U   /*!< GPIO pin number */
#define BOARD_INITMIPIPANELPINS_LCD_RST_B_GPIO_PIN_MASK              (1U << 14U)   /*!< GPIO pin mask */

/* GPIO_EMC_B2_03 (coord R1), DSI_BL_PWM */
/* Routed pin properties */
#define BOARD_INITMIPIPANELPINS_DSI_BL_PWM_PERIPHERAL                      GPIO8   /*!< Peripheral name */
#define BOARD_INITMIPIPANELPINS_DSI_BL_PWM_SIGNAL                        gpio_io   /*!< Signal name */
#define BOARD_INITMIPIPANELPINS_DSI_BL_PWM_CHANNEL                           13U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMIPIPANELPINS_DSI_BL_PWM_GPIO                            GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITMIPIPANELPINS_DSI_BL_PWM_GPIO_PIN                          13U   /*!< GPIO pin number */
#define BOARD_INITMIPIPANELPINS_DSI_BL_PWM_GPIO_PIN_MASK             (1U << 13U)   /*!< GPIO pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitMipiPanelPins(void);           /* Function assigned for the Cortex-M7F */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
