/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v9.0
processor: MIMXRT1176xxxxx
package_id: MIMXRT1176DVMAA
mcu_data: ksdk2_0
processor_version: 9.0.1
board: MIMXRT1170-EVK
pin_labels:
- {pin_num: R1, pin_signal: GPIO_EMC_B2_03, label: DSI_BL_PWM, identifier: DSI_BL_PWM}
- {pin_num: K2, pin_signal: GPIO_EMC_B2_00, label: LPI2C2_SCL, identifier: LPI2C2_SCL}
- {pin_num: K4, pin_signal: GPIO_EMC_B2_01, label: LPI2C2_SDA, identifier: LPI2C2_SDA}
- {pin_num: N12, pin_signal: GPIO_AD_00}
- {pin_num: R14, pin_signal: GPIO_AD_01}
- {pin_num: A4, pin_signal: GPIO_DISP_B2_15, label: 'WDOG_B/LCM_PWR_EN/J48[32]', identifier: DSI_EN}
- {pin_num: P13, pin_signal: GPIO_AD_05, label: DSI_TS_RST, identifier: DSI_TS_RST}
- {pin_num: R16, pin_signal: GPIO_AD_09, label: DSI_RST, identifier: DSI_RST}
- {pin_num: M14, pin_signal: GPIO_AD_15, label: LCD_RST_B, identifier: LCD_RST_B}
- {pin_num: M17, pin_signal: GPIO_AD_29, label: DSI_EN, identifier: DSI_EN}
- {pin_num: K17, pin_signal: GPIO_AD_30, label: DSI_TS_INT, identifier: DSI_TS_INT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "fsl_common.h"
#include "fsl_iomuxc.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 * 
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 * 
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void) {
    BOARD_InitLpuartPins();
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitLpuartPins:
- options: {callFromInitBoot: 'true', coreID: cm7, enableClock: 'true'}
- pin_list:
  - {pin_num: M15, peripheral: LPUART1, signal: RXD, pin_signal: GPIO_AD_25, software_input_on: Enable, pull_up_down_config: Pull_Down, pull_keeper_select: Keeper,
    open_drain: Disable, drive_strength: Normal, slew_rate: Slow}
  - {pin_num: L13, peripheral: LPUART1, signal: TXD, pin_signal: GPIO_AD_24, pull_up_down_config: Pull_Down, pull_keeper_select: Keeper, open_drain: Disable, drive_strength: Normal,
    slew_rate: Slow}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitLpuartPins, assigned for the Cortex-M7F core.
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitLpuartPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* LPCG on: LPCG is ON. */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_24_LPUART1_TXD,          /* GPIO_AD_24 is configured as LPUART1_TXD */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_25_LPUART1_RXD,          /* GPIO_AD_25 is configured as LPUART1_RXD */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_AD_25 */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AD_24_LPUART1_TXD,          /* GPIO_AD_24 PAD functional properties : */
      0x00U);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: normal drive strength
                                                 Pull / Keep Select Field: Pull Disable, Highz
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain Field: Disabled
                                                 Domain write protection: Both cores are allowed
                                                 Domain write protection lock: Neither of DWP bits is locked */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AD_25_LPUART1_RXD,          /* GPIO_AD_25 PAD functional properties : */
      0x00U);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: normal drive strength
                                                 Pull / Keep Select Field: Pull Disable, Highz
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain Field: Disabled
                                                 Domain write protection: Both cores are allowed
                                                 Domain write protection lock: Neither of DWP bits is locked */
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitMipiPanelPins:
- options: {callFromInitBoot: 'false', coreID: cm7, enableClock: 'true'}
- pin_list:
  - {pin_num: M17, peripheral: GPIO9, signal: 'gpio_io, 28', pin_signal: GPIO_AD_29, gpio_init_state: no_init, pull_up_down_config: Pull_Up, pull_keeper_select: Pull,
    drive_strength: High}
  - {pin_num: K2, peripheral: LPI2C2, signal: SCL, pin_signal: GPIO_EMC_B2_00, software_input_on: Enable, pdrv_config: no_init, open_drain: Enable}
  - {pin_num: K4, peripheral: LPI2C2, signal: SDA, pin_signal: GPIO_EMC_B2_01, software_input_on: Enable, pull_down_pull_up_config: Pull_Down, pdrv_config: no_init,
    open_drain: Enable}
  - {pin_num: K17, peripheral: GPIO9, signal: 'gpio_io, 29', pin_signal: GPIO_AD_30, gpio_interrupt: no_init, software_input_on: Enable, pull_up_down_config: Pull_Down,
    pull_keeper_select: no_init, drive_strength: Normal}
  - {pin_num: P13, peripheral: GPIO9, signal: 'gpio_io, 04', pin_signal: GPIO_AD_05, gpio_init_state: no_init, pull_up_down_config: Pull_Down, pull_keeper_select: no_init,
    open_drain: Disable, drive_strength: Normal, slew_rate: Slow}
  - {pin_num: M14, peripheral: GPIO9, signal: 'gpio_io, 14', pin_signal: GPIO_AD_15, pull_keeper_select: no_init}
  - {pin_num: R1, peripheral: GPIO8, signal: 'gpio_io, 13', pin_signal: GPIO_EMC_B2_03, gpio_init_state: no_init, pull_down_pull_up_config: Pull_Down, pdrv_config: Normal_Driver}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitMipiPanelPins, assigned for the Cortex-M7F core.
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitMipiPanelPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* LPCG on: LPCG is ON. */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_05_GPIO9_IO04,           /* GPIO_AD_05 is configured as GPIO9_IO04 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_15_GPIO9_IO14,           /* GPIO_AD_15 is configured as GPIO9_IO14 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_29_GPIO9_IO28,           /* GPIO_AD_29 is configured as GPIO9_IO28 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_30_GPIO9_IO29,           /* GPIO_AD_30 is configured as GPIO9_IO29 */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_AD_30 */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B2_00_LPI2C2_SCL,       /* GPIO_EMC_B2_00 is configured as LPI2C2_SCL */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_EMC_B2_00 */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B2_01_LPI2C2_SDA,       /* GPIO_EMC_B2_01 is configured as LPI2C2_SDA */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_EMC_B2_01 */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B2_03_GPIO8_IO13,       /* GPIO_EMC_B2_03 is configured as GPIO8_IO13 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AD_05_GPIO9_IO04,           /* GPIO_AD_05 PAD functional properties : */
      0x04U);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: normal drive strength
                                                 Pull / Keep Select Field: Pull Enable
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain Field: Disabled
                                                 Domain write protection: Both cores are allowed
                                                 Domain write protection lock: Neither of DWP bits is locked */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AD_29_GPIO9_IO28,           /* GPIO_AD_29 PAD functional properties : */
      0x0EU);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: high drive strength
                                                 Pull / Keep Select Field: Pull Enable
                                                 Pull Up / Down Config. Field: Weak pull up
                                                 Open Drain Field: Disabled
                                                 Domain write protection: Both cores are allowed
                                                 Domain write protection lock: Neither of DWP bits is locked */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AD_30_GPIO9_IO29,           /* GPIO_AD_30 PAD functional properties : */
      0x04U);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: normal drive strength
                                                 Pull / Keep Select Field: Pull Enable
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain Field: Disabled
                                                 Domain write protection: Both cores are allowed
                                                 Domain write protection lock: Neither of DWP bits is locked */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_EMC_B2_00_LPI2C2_SCL,       /* GPIO_EMC_B2_00 PAD functional properties : */
      0x18U);                                 /* PDRV Field: high drive strength
                                                 Pull Down Pull Up Field: Internal pulldown resistor enabled
                                                 Open Drain Field: Enabled
                                                 Domain write protection: Both cores are allowed
                                                 Domain write protection lock: Neither of DWP bits is locked */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_EMC_B2_01_LPI2C2_SDA,       /* GPIO_EMC_B2_01 PAD functional properties : */
      0x18U);                                 /* PDRV Field: high drive strength
                                                 Pull Down Pull Up Field: Internal pulldown resistor enabled
                                                 Open Drain Field: Enabled
                                                 Domain write protection: Both cores are allowed
                                                 Domain write protection lock: Neither of DWP bits is locked */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_EMC_B2_03_GPIO8_IO13,       /* GPIO_EMC_B2_03 PAD functional properties : */
      0x0AU);                                 /* PDRV Field: normal drive strength
                                                 Pull Down Pull Up Field: Internal pulldown resistor enabled
                                                 Open Drain Field: Disabled
                                                 Domain write protection: Both cores are allowed
                                                 Domain write protection lock: Neither of DWP bits is locked */
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
